### ISSUE TITLE
[Feature Request] Increase usefulness of data-autofill

### ISSUE THREAD

**Issue by JamesHill3** [craigbuckler/datalist-ajax#1]
First, thanks for making this useful module!

I'm currently attempting to use `<auto-complete />` inside of a grid where each row contains a single `<auto-complete />`. I assign each `<auto-complete />` a unique id based on its position in the array being iterated to generate the rows. I then use **data-autofill** to populate a hidden input with the actual value, in this case a unique ID, that I need from the AJAX response. This is where I'm having an issue.

Because data-autofill uses a name selector, all hidden input values are being updated. A supporting data attribute like the example below would be really useful in cases where multiple `<auto-complete />`'s are used on a single page to fetch similar results. See example below.

```
<auto-complete api="@Request.Path?handler=PlantItemSearch&query=${plantItemDataList_@i}&plantId=@Model.PlantId&fields=plantItemId;itemNumber;itemName"
    resultname="itemNumber"
    querymin="2"
    optionmax="50"
    inputdelay="150">
        <input type="text" id="plantItemDataList_@i" name="plantItemDataList_@i" autocomplete="off" placeholder="Enter Item Name or Number" value="@itemNumber" />
</auto-complete>
<input type="hidden" 
            name="@namePrefix.@(nameof(PurchaseOrderDetailAddEdit.PlantItemId))"
            value="@poDetail.PlantItemId"
            data-autofill="plantItemId"
            data-autofill-source="id="plantItemDataList_@i"" />
```

Admittedly, I haven't dug into the complexity of the code, but on the face of it, it seems like `data-autofill-source` could be added as an optional argument simply by updating this selector:

```
Array.from(this.input.form.querySelectorAll(`[data-autofill="${ name }"]`)).forEach(f => {
    f.value = data[name] || '';
    reset[name] = '';
});
```

To this:

```
Array.from(this.input.form.querySelectorAll(`[data-autofill="${name}"]:not([data-autofill-source]), [data-autofill="${name}"][data-autofill-source="${(this.input.name || this.input.id)}"]`)).forEach(f => {
    f.value = data[name] || '';
    reset[name] = '';
});
```

Alternatively, exposing a custom change event that includes all fields in the fields query string param could also work, although it seems less elegant. Thoughts?

**Comment by craigbuckler** [comment]
Thanks @JamesHill3.

You appear to have quite an unusual problem and I'm still trying to get my head around it!

I agree there's an issue with auto-filling - it's too imprecise if you have similar API results. Your `data-autofill-source` solution is an option, but it feels a little complex. A custom event seems a great idea, but I'll have a think about some options.

Craig

**Comment by JamesHill3** [comment]
Thanks for responding, @craigbuckler . Just in case I've done a poor job explaining myself, I've put together a couple of fiddles that do a better job of demonstrating what I'm trying to overcome.

[The issue I'm trying to overcome is demonstrated here.](https://codepen.io/jamesh3/pen/zYZoLBM) In this quick and dirty adaptation of your original codepen demo, I'm collecting two countries - the country I currently live in and the country I want to live in. Notice what happens to the auto-fill's when the first country is populated.

[My proposed solution can be found here.](https://codepen.io/jamesh3/pen/ZEeBjrm) Take note that if a `data-autofill-source` is not provided, it will simply default to the current functionality.

Do the demos help? Does it confirm your suspicion that it's too complex, or have you fallen madly in love with the idea :-)?

**Comment by craigbuckler** [comment]
Your description was good, but thanks for the examples - it confirmed my suspicions.

Your solution works, but the complex selector in `data-autofill-source` could confuse many. It took me some time to work it out!

My current thoughts...

1. I like the idea of triggering an event so I'll probably do that anyway.
2. It might be practical to support an optional `id`, e.g `<auto-complete id="country1" api="...">`. That could then be used as a namespace for auto-filling, e.g. `data-autofill="#country1.name"` (existing`data-autofill="name"` functionality would still be supported).

That's possibly easier to use? Would it help your situation?

**Comment by JamesHill3** [comment]
@craigbuckler Both the event or the namespace idea would work for me. Thanks!

**Comment by craigbuckler** [comment]
Thanks @JamesHill3. That's great. I'll sleep on it then get an update done shortly.
Appreciate the suggestions and feedback.

**Comment by JamesHill3** [comment]
@craigbuckler Thanks for the update! I think that the way you've handled it is very clean.

**Comment by craigbuckler** [comment]
To be fair, it's very similar to your solution so thanks for the suggestion!
